
server:
  port: 8082

spring:
  thymeleaf:
    cache: false
  application:
      name: fortify-report-service



logging:
  level:
    root: INFO
    com.fortify: DEBUG
    org.springframework.web.client.RestClient: INFO

fortify:
  ssc:
    baseUrl: https://fortifyssc.int.corp.sun/ssc/api/v1
    authHeaderPrefix: FortifyToken
    token: ZTM3MTljNTItMzI3NCO0NDY3OUtLIyMTODI2YjNTk0YWZk


  apps:
    Broker-Notifications-Service: "1753"
    AMP-Home: "1502"
    DigitalNZ-Motor-New: "1680"
    DigitalNZ-AAI-PSS: "1709"
